version: '{build}-{branch}'
branches:
  only:
    - master

skip_tags: true

image:
- Visual Studio 2015

environment:
  matrix:
    - image: Visual Studio 2017
      configuration: Release
      arch: 64

clone_folder: c:\projects\catboost

install:
  - git submodule update --init --recursive
  
artifacts:
  - path: catboost/cuda/app/cb_cuda.exe
  - path: '**\*.whl'

deploy:
  provider: GitHub
  auth_token:
    secure: 0UtNN1WVxsjuNRHVn7bmrRM86gKZ/RjtGzBbhWZFIqNSG/I8vTUofgrD7wnlAp6z
  artifact: catboost/cuda/app/cb_cuda.exe, '**\*.whl'
  on:
    branch: master

build_script:
  - |
    echo Downloading CUDA toolkit 8
    appveyor DownloadFile  https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda_8.0.44_windows-exe -FileName cuda_8.0.44_windows.exe
    echo Installing CUDA toolkit 8
    cuda_8.0.44_windows.exe -s compiler_8.0 cublas_8.0 cublas_dev_8.0 cudart_8.0 curand_8.0 curand_dev_8.0 cusparse_8.0 cusparse_dev_8.0

    dir .

    dir "%ProgramFiles%"
    dir "C:\Program Files"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin"

    set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;%PATH%

    nvcc -V
    cd c:\projects\catboost
    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    call ya.bat make -o . --verbose --stat -r catboost\cuda\app -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
    cd catboost\python-package
    C:\Python27-x64\python.exe mk_wheel.py -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
    C:\Python35-x64\python.exe mk_wheel.py -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
    C:\Python36-x64\python.exe mk_wheel.py -DCUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
