sudo: required
cache:
  timeout: 1000
  packages: true
  apt: true
  directories:
    - $HOME/.ya

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libc6-dev
      - python-dev
      - python3-dev

before_script: |
    # `ya` provides it's own compiler toolchains, `CC` and CXX` environment variables will override
    # them so we have to unset them.
    #
    unset CC
    unset CXX

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      language: cpp
      env: CB_BUILD_AGENT='clang-darwin-x86_64-release' CACHE_NAME=darwin
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: catboost-darwin
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      osx_image: xcode8.2
      language: cpp
      env: CB_BUILD_AGENT='clang-darwin-x86_64-release-cuda' CACHE_NAME=darwin
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: catboost-cuda-darwin
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      osx_image: xcode8.2
      language: cpp
      env: CB_BUILD_AGENT='python2-darwin-x86_64-release' CACHE_NAME=darwin
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: catboost/python-package/*.whl
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      osx_image: xcode8.2
      language: cpp
      env: CB_BUILD_AGENT='python35-darwin-x86_64-release' CACHE_NAME=darwin
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: catboost/python-package/*.whl
        skip_cleanup: true
        on:
          tags: true
    - os: osx
      osx_image: xcode8.2
      language: cpp
      env: CB_BUILD_AGENT='python36-darwin-x86_64-release' CACHE_NAME=darwin
      script: ~/build/${TRAVIS_REPO_SLUG}/ci/travis/script.sh
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: catboost/python-package/*.whl
        skip_cleanup: true
        on:
          tags: true
